<?php
/**
 * Created by PhpStorm.
 * User: xiaotian
 * Date: 2019/8/1
 * Time: 18:18
 */

namespace app\admin\controller;


use think\Controller;
use think\Session;
use app\admin\model\Admin as AdminModel;
use app\admin\model\Menu as MenuModel;
class Base extends Controller
{
    private $login;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->login=Session::has('admin_id')?Session::get('admin_id'):'';
    }
    protected function is_login(){
        if($this->login){
            $this->success('已登入，无需再次登入',url('index/index'));
        }
    }
    protected function no_login(){
        if(!$this->login){
            $this->error('请登入后操作',url('login/index'));
        }
    }

    protected function menu_lists(){
        $id=Session::get("admin_id");
        $admin=AdminModel::get(['id'=>$id]);
        $role=json_decode($admin['role']['right']);
        $roles=array('in',$role);
        $menu=MenuModel::where(array('pid'=>0,'id'=>$roles,'is_hidden'=>0,'status'=>1))->order('ord asc')->select();
        foreach($menu as $vo){
            $array=MenuModel::where(array('pid'=>$vo['id'],'id'=>$roles,'is_hidden'=>0,'status'=>1))->select();
            $menu_name[$vo['name']]=$array;

        }
        return $menu_name;
    }
}