<?php
/**
 * Created by PhpStorm.
 * User: xiaotian
 * Date: 2019/8/1
 * Time: 17:59
 */

namespace app\home\controller;


use think\Controller;
use think\Session;

class Base extends Controller
{
    private $login;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->login=Session::has('user_info')?Session::get('user_info'):'';
    }
    protected function is_login(){
        if($this->login){
            $this->success('已登入，无需再次登入',url('/'));
        }
    }
    protected function no_loginBefore(){
        if(!$this->login){
            return  [
              'status'=>0,
                'message'=>'请点击右上角登入后可操作哦',
            ];
        }
      return "true";
    }

    protected function no_login(){
        if(!$this->login){
            $this->error('请登入',url('/'));
        }
    }

    protected function getUid(){
        return Session::get('user_info.id');
    }

}